use chrono::prelude::*;
use serde_json::{Result, Value};
use serde::{Serialize, Deserialize};

use crate::models::{Learner, Registration, Location, 
    PhysicalInfrastructure, test_plot,
    DigitalInfrastructure, Personnel, Group, DeliveryRole,
    LearningProduct, Module, Audience, Role, BusinessLine,
    Status, LearningStyle, LearningObjective, ContentType, LearningObjectiveResponse,
    Objective, Organization};

use crate::models::demographic::{Pronouns, Sexuality, Ethnicity, Language};

#[derive(Serialize, Deserialize, Debug)]
pub struct EvalCSV {
    pub eval_id: u32,

    // Learner
    pub learner_id: u32,
    pub audience: Audience,
    pub group: Group,
    pub level: usize,
    pub role: Role,
    pub organization: Organization,
    pub pronouns: Pronouns,
    pub sexuality: Sexuality,
    pub ethnicity: Ethnicity,
    pub language: Language,
    pub person_with_disability: bool,
    pub openness: f64,
    pub exclusion: f64,

    // Product
    pub registration_id: u32,
    pub offering_id: u32,
    pub learning_product: String,
    pub business_line: BusinessLine,
    pub content: ContentType,
    pub duration: u32,
    pub module: usize, 
    pub date_stamp: String,
    pub objective: Objective,

    // Skill
    pub current_skill: u32,
    pub desired_skill: u32,
    pub final_skill: u32,

    // Evaluation
    pub recommend: bool, 
    pub rating: usize, 
    pub clear: bool, 
    pub entertaining: bool,
    pub relevant: bool, 
    pub informative: bool, 
    pub useful: bool, 
    pub inclusive: bool, 
    pub easy: bool, 
    pub difficult: bool, 
    pub long: bool, 
    pub short: bool,
    pub percent_completed: f64,
    pub lo_1: LearningObjectiveResponse, 
    pub lo_2: LearningObjectiveResponse,

    // Physical Eval
    pub physical_space: bool,
    pub physical_clean: bool,
    pub physical_comfortable: bool,
    pub physical_professional: bool,
    pub physical_pleasant: bool,
    pub physical_accessible: bool,

    // Digital Eval
    pub digital_content: bool,
    pub digital_smooth: bool,
    pub digital_professional: bool,
    pub digital_accessible: bool,

    // Personnel Eval
    pub personnel_present: bool,
    pub personnel_pleasant: bool,
    pub personnel_helpful: bool,
    pub personnel_professional: bool,
    pub personnel_inclusive: bool,
    pub personnel_knowledgeable: bool,
}

impl EvalCSV {
    pub fn new(
        eval_id: u32,
        learner_id: u32,
        audience: Audience,
        group: Group,
        level: usize,
        role: Role,
        organization: Organization,
        pronouns: Pronouns,
        sexuality: Sexuality,
        ethnicity: Ethnicity,
        language: Language,
        person_with_disability: bool,
        openness: f64,
        exclusion: f64,
        registration_id: u32,
        offering_id: u32,
        learning_product: String,
        business_line: BusinessLine,
        content: ContentType,
        duration: u32,
        module: usize, 
        date_stamp: String,
        objective: Objective,
        current_skill: u32,
        desired_skill: u32,
        final_skill: u32,
        recommend: bool, 
        rating: usize, 
        clear: bool, 
        entertaining: bool,
        relevant: bool, 
        informative: bool, 
        useful: bool, 
        inclusive: bool, 
        easy: bool, 
        difficult: bool, 
        long: bool, 
        short: bool, 
        percent_completed: f64,
        lo_1: LearningObjectiveResponse, 
        lo_2: LearningObjectiveResponse,
        // Physical Eval
        physical_space: bool,
        physical_clean: bool,
        physical_comfortable: bool,
        physical_professional: bool,
        physical_pleasant: bool,
        physical_accessible: bool,

        // Digital Eval
        digital_content: bool,
        digital_smooth: bool,
        digital_professional: bool,
        digital_accessible: bool,

        // Personnel Eval
        personnel_present: bool,
        personnel_pleasant: bool,
        personnel_helpful: bool,
        personnel_professional: bool,
        personnel_inclusive: bool,
        personnel_knowledgeable: bool,
    ) -> Self {
        EvalCSV {
            eval_id: eval_id,
            learner_id: learner_id,
            audience: audience,
            group: group,
            level: level,
            role: role,
            organization: organization,
            pronouns: pronouns,
            sexuality: sexuality,
            ethnicity: ethnicity,
            language: language,
            person_with_disability: person_with_disability,
            openness: openness,
            exclusion: exclusion,
            registration_id: registration_id,
            offering_id: offering_id,
            learning_product: learning_product,
            business_line: business_line,
            content: content,
            duration: duration,
            module: module, 
            date_stamp: date_stamp,
            objective: objective,
            current_skill: current_skill,
            desired_skill: desired_skill,
            final_skill: final_skill,
            recommend: recommend, 
            rating: rating, 
            clear: clear, 
            entertaining: entertaining,
            relevant: relevant, 
            informative: informative, 
            useful: useful, 
            inclusive: inclusive, 
            easy: easy, 
            difficult: difficult, 
            long: long, 
            short: short,
            percent_completed: percent_completed, 
            lo_1: lo_1, 
            lo_2: lo_2,
            physical_space: physical_space,
            physical_clean: physical_clean,
            physical_comfortable: physical_comfortable,
            physical_professional: physical_professional,
            physical_pleasant: physical_pleasant,
            physical_accessible: physical_accessible,
            digital_content: digital_content,
            digital_smooth: digital_smooth,
            digital_professional: digital_professional,
            digital_accessible: digital_accessible,
            personnel_present: personnel_present,
            personnel_pleasant: personnel_pleasant,
            personnel_helpful: personnel_helpful,
            personnel_professional: personnel_professional,
            personnel_inclusive: personnel_inclusive,
            personnel_knowledgeable: personnel_knowledgeable,
        }
    }
}